# Gitpod 配置文件
image:
  file: .gitpod.dockerfile

ports:
  - port: 8080
    onOpen: ignore
  - port: 8081
    onOpen: ignore

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - google.dart-code
    - JetBrains.kotlin

# 启动任务
tasks:
  - name: 初始化环境
    command: |
      echo "Gitpod 环境初始化完成"
      echo "使用 ./build-apk.sh 命令构建 APK"

# 持久化存储
workspaceStorage:
  enabled: true